VAGRANT_EXPERIMENTAL = "disks"
MASTER_IP = "192.168.42.110"
MEMORY_SIZE = 1024
CPU_NUM = 1

Vagrant.configure("2") do |config|
######################
### Master NODE ######
######################
  config.vm.define "bdomitil_Kuber" do | v|

    v.vm.box = "centos7"
    v.vm.hostname = "kuber-machineS"
    v.vm.network "private_network", ip: MASTER_IP
    # v.disksize.size = '20GB' #vagrant plugin install disksize
    v.vm.provider "virtualbox" do | vb |
      vb.name = "bdomitil"
      vb.memory = MEMORY_SIZE
      vb.cpus = CPU_NUM
    end
    v.vm.provision "shell", args: [ MASTER_IP ], inline: <<-SHELL
      echo "$2  SlaveSW" > /etc/hosts
     curl -sfL https://get.k3s.io | sh -s -  --write-kubeconfig-mode 644 --node-name  k3s-master --node-external-ip $1 --advertise-address $1 
     yum install nano -y
     echo export PATH="/usr/local/bin/:$PATH" > ~/.bashrc
     source ~/.bashrc
     kubectl apply -f /vagrant/app1.yaml
     kubectl apply -f /vagrant/app2.yaml
     kubectl apply -f /vagrant/app3.yaml
  SHELL
  end
end


