VAGRANT_EXPERIMENTAL = "disks"
MASTER_IP = "192.168.42.110"
MEMORY_SIZE = 4048
CPU_NUM = 6
ARGO_INSTALL_FILE = "/vagrant/scripts/argo_install.sh"

Vagrant.configure("2") do |config|
######################
### Master NODE ######
######################
  config.vm.define "bdomitil_Argo" do | v|

    v.vm.box = "centos7"
    v.vm.hostname = "argo-ci"
    v.vm.network "private_network", ip: MASTER_IP
    # v.disksize.size = '20GB' #vagrant plugin install disksize
    v.vm.provider "virtualbox" do | vb |
      vb.name = "bdomitil_ARGO"
      vb.memory = MEMORY_SIZE
      vb.cpus = CPU_NUM
    end
    v.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"

    v.vm.provision "shell",  args: [ MASTER_IP, ARGO_INSTALL_FILE ], inline: <<-SHELL
    echo export PATH="/usr/local/bin/:$PATH" > ~/.bashrc
    source ~/.bashrc
    cat ~/.ssh/me.pub >> ~/.ssh/authorized_keys
    cat ~/.ssh/me.pub  >> /home/vagrant/.ssh/authorized_keys
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" 
     install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
     yum install nano -y
     yum install -y yum-utils
     yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
     yum install -y docker-ce docker-ce-cli containerd.io
     systemctl enable docker
     systemctl start docker
     usermod -aG docker vagrant
     curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=v5.0.0 bash
     k3d cluster create argoCluster -a 4 --api-port localhost:6444
     if [ -f "$2" ]
      then 
      chmod +x $2
      bash $2
     fi
  SHELL
  end
end


